version: '3.9'
services:
  converter_service:
    env_file:
      -  .env
    image: $CONVERTER_SERVICE_NAME
    container_name: $CONVERTER_SERVICE_NAME
    build: $CONVERTER_SERVICE_BUILD
    ports:
      - $CONVERTER_SERVICE_EXPOSE_PORT:$CONVERTER_SERVICE_PORT
    expose:
      - $CONVERTER_SERVICE_EXPOSE_PORT
    environment:
      PORT: $CONVERTER_SERVICE_PORT
      FFMPEG: $FFMPEG
      MAGICK: $MAGICK
      UPLOADS_PATH_PDF: $UPLOADS_PATH_PDF
      UPLOADS_PATH_AUDIO: $UPLOADS_PATH_AUDIO
      UPLOADS_PATH_IMAGE: $UPLOADS_PATH_IMAGE
      UPLOADS_PATH_VIDEO: $UPLOADS_PATH_VIDEO
      DOWNLOAD_PATH_AUDIO: $DOWNLOAD_PATH_AUDIO
      DOWNLOAD_PATH_IMAGE: $DOWNLOAD_PATH_IMAGE
      DOWNLOAD_PATH_VIDEO: $DOWNLOAD_PATH_VIDEO
      DOWNLOAD_PATH_PDF: $DOWNLOAD_PATH_PDF
    restart: always