
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 300
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end
  #provision with docker
  config.vm.provision :docker


  #VM 1 ci-server
  config.vm.define "ci-server" do |ciserver|
    ciserver.vm.network "private_network", ip: '192.168.56.60'
    ciserver.vm.hostname = "ci-server"
    ciserver.vm.provision :file, source:"../docker/docker-compose.ci.yaml", destination:"docker-compose.yaml"
    ciserver.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yaml", run: "always"
    ciserver.vm.provision :shell, inline:"sudo chmod 777 /var/run/docker.sock"

  end


  #VM 2 server-2
  config.vm.define "server-2" do |server2|
    server2.vm.network "private_network", ip: '192.168.56.61'
    server2.vm.hostname = "server-2"

  end
end
