FROM gocd/gocd-agent-ubuntu-20.04:v22.2.0
USER root
RUN apt-get update \
    && curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && apt-get install nodejs \
    apt-get autoremove -y && \
    apt-get clean
USER go